name = "MicroMamba"
uuid = "0b3b1443-0f03-428d-bdfb-f27f9c1191ea"
authors = ["Christopher Rowley <github.com/cjdoris>"]
version = "0.1.14"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
micromamba_jll = "f8abcde7-e9b7-5caa-b8af-a437887ae8e4"

[compat]
Scratch = "1.1"
julia = "1.6"
micromamba_jll = "0.26, 1 - 1.4.2, 1.4.7, 2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
